definitions:
  api-gateway_pkg_api_auth_v1.GetUsersInfoResponse:
    properties:
      users:
        additionalProperties:
          $ref: '#/definitions/api-gateway_pkg_api_auth_v1.UserInfo'
        description: Возвращаем map, где ключ - user_id.
        type: object
    type: object
  api-gateway_pkg_api_auth_v1.LoginResponse:
    properties:
      access_token:
        description: JWT-токен
        type: string
    type: object
  api-gateway_pkg_api_auth_v1.RegisterResponse:
    properties:
      access_token:
        description: JWT-токен
        type: string
    type: object
  api-gateway_pkg_api_auth_v1.UserInfo:
    properties:
      id:
        type: string
      login:
        type: string
      name:
        type: string
    type: object
  api-gateway_pkg_api_v1.CancelEventResponse:
    properties:
      success:
        description: Успешно/ не успешно
        type: boolean
    type: object
  api-gateway_pkg_api_v1.CreateEventResponse:
    properties:
      id:
        type: string
    type: object
  api-gateway_pkg_api_v1.EventInfo:
    properties:
      description:
        description: Описание мероприятия
        type: string
      duration:
        description: Длительность мероприятия
        type: integer
      id:
        type: string
      is_private:
        description: Приватность
        type: boolean
      starts_at:
        allOf:
        - $ref: '#/definitions/timestamppb.Timestamp'
        description: Дата-время начала мероприятия
      status:
        description: Статус мероприятия (draft / active / cancelled / completed)
        type: string
      title:
        description: Название мероприятия
        type: string
    type: object
  api-gateway_pkg_api_v1.GetEventResponse:
    properties:
      event:
        allOf:
        - $ref: '#/definitions/api-gateway_pkg_api_v1.EventInfo'
        description: Само мероприятие
    type: object
  api-gateway_pkg_api_v1.ListEventsResponse:
    properties:
      events:
        description: Список всех мероприятий
        items:
          $ref: '#/definitions/api-gateway_pkg_api_v1.EventInfo'
        type: array
    type: object
  api-gateway_pkg_api_v1.ListUserEventsResponse:
    properties:
      events:
        description: Список ивентов
        items:
          $ref: '#/definitions/api-gateway_pkg_api_v1.EventInfo'
        type: array
    type: object
  api-gateway_pkg_api_v1.UpdateEventResponse:
    properties:
      event:
        $ref: '#/definitions/api-gateway_pkg_api_v1.EventInfo'
    type: object
  api-gateway_pkg_response.ErrorResponse:
    properties:
      error:
        properties:
          code:
            type: string
          message:
            type: string
        type: object
    type: object
  internal_transport_handlers_authorization.GetUsersInfoDTO:
    properties:
      user_ids:
        items:
          type: string
        type: array
    type: object
  internal_transport_handlers_authorization.LoginDTO:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  internal_transport_handlers_authorization.RegisterDTO:
    properties:
      email:
        type: string
      login:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  internal_transport_handlers_event.CreateEventDTO:
    properties:
      description:
        type: string
      duration_minutes:
        type: integer
      is_private:
        type: boolean
      location_coords:
        type: string
      location_name:
        type: string
      max_participants:
        type: integer
      starts_at:
        type: string
      title:
        type: string
    type: object
  internal_transport_handlers_event.UpdateEventDTO:
    properties:
      description:
        type: string
      location_coords:
        type: string
      location_name:
        type: string
      starts_at:
        type: string
      title:
        type: string
    type: object
  timestamppb.Timestamp:
    properties:
      nanos:
        description: |-
          Non-negative fractions of a second at nanosecond resolution. This field is
          the nanosecond portion of the duration, not an alternative to seconds.
          Negative second values with fractions must still have non-negative nanos
          values that count forward in time. Must be between 0 and 999,999,999
          inclusive.
        type: integer
      seconds:
        description: |-
          Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must
          be between -315576000000 and 315576000000 inclusive (which corresponds to
          0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z).
        type: integer
    type: object
info:
  contact: {}
  title: Eventify API Gateway
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Принимает email и пароль, возвращает JWT токен
      parameters:
      - description: Данные для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_transport_handlers_authorization.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: вернёт access_token
          schema:
            $ref: '#/definitions/api-gateway_pkg_api_auth_v1.LoginResponse'
        "400":
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "401":
          description: Неверный логин или пароль
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
      summary: Авторизация пользователя
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя и возвращает JWT токен
      parameters:
      - description: Данные для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_transport_handlers_authorization.RegisterDTO'
      produces:
      - application/json
      responses:
        "200":
          description: вернет access_token
          schema:
            $ref: '#/definitions/api-gateway_pkg_api_auth_v1.RegisterResponse'
        "400":
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "409":
          description: Пользователь с таким email или логином уже существует
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
      summary: Регистрация пользователя
      tags:
      - auth
  /users/{login}:
    get:
      description: Ищет пользователя по уникальному логину (никнейму) и возвращает
        его публичные данные
      parameters:
      - description: Логин пользователя (без @)
        in: path
        name: login
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Публичные данные пользователя
          schema:
            $ref: '#/definitions/api-gateway_pkg_api_auth_v1.UserInfo'
        "400":
          description: Логин не передан
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
      summary: Получение публичного профиля пользователя
      tags:
      - users
  /users/info:
    post:
      consumes:
      - application/json
      description: Возвращает мапу с данными пользователей по переданному массиву
        ID
      parameters:
      - description: Массив UUID пользователей
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_transport_handlers_authorization.GetUsersInfoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Map пользователей (ключ - ID)
          schema:
            $ref: '#/definitions/api-gateway_pkg_api_auth_v1.GetUsersInfoResponse'
        "400":
          description: Неверный формат запроса
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "404":
          description: Пользователи не найдены
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
      summary: Получение информации о группе пользователей
      tags:
      - users
  /v1/events:
    get:
      consumes:
      - application/json
      description: 'Получение списка ивентов. Также можно через query-параметры указать:
        поиск по названию (title), поиск по описанию (description); фильтрация по
        дате: (starts_after, starts_before), фильтр по локации (location_name)'
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает список ивентов
          schema:
            $ref: '#/definitions/api-gateway_pkg_api_v1.ListEventsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
      summary: Получить список ивентов
      tags:
      - events
    post:
      consumes:
      - application/json
      description: Создает ивент. Обязательно передавать Bearer токен в заголовке
        Authorization.
      parameters:
      - description: Данные мероприятия
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_transport_handlers_event.CreateEventDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает ID созданного ивента
          schema:
            $ref: '#/definitions/api-gateway_pkg_api_v1.CreateEventResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Создать новое мероприятие
      tags:
      - events
  /v1/events/{event_id}:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 'Возвращает список: обновлённые данные об ивенте'
          schema:
            $ref: '#/definitions/api-gateway_pkg_api_v1.CancelEventResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Отменить ивент
      tags:
      - events
    get:
      consumes:
      - application/json
      description: отправляется id ивента, возвращается информация о нём
      produces:
      - application/json
      responses:
        "200":
          description: 'Возвращает список: информация об ивенте'
          schema:
            $ref: '#/definitions/api-gateway_pkg_api_v1.GetEventResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
      summary: получить информацию об ивенте
      tags:
      - events
    patch:
      consumes:
      - application/json
      description: Частичное обновление данных (PATCH). Обязательно Bearer токен.
      parameters:
      - description: ID мероприятия
        in: path
        name: event_id
        required: true
        type: string
      - description: Новые данные
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_transport_handlers_event.UpdateEventDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api-gateway_pkg_api_v1.UpdateEventResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Обновить мероприятие
      tags:
      - events
  /v1/events/my:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает список мероприятий пользователя
          schema:
            $ref: '#/definitions/api-gateway_pkg_api_v1.ListUserEventsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api-gateway_pkg_response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Список мероприятий пользователя
      tags:
      - events
securityDefinitions:
  BearerAuth:
    description: API для сервиса мероприятий Eventify
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
